# EXPECT-STATUS: 200
# EXPECT-HEADER: Transfer-Encoding: chunked
# EXPECT-HEADER: Content-Type:
# EXPECT-BODY: REQUEST_METHOD
# EXPECT-BODY: GET

GET /test-cgi.cgi HTTP/1.1
Host: host1.cs.yale.edu
Accept: text/html

